-- Dans ~/.config/nvim/lua/plugins/lspconfig.lua
return {
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        phpactor = {
          cmd = { "phpactor", "language-server" },
          filetypes = { "php" },
          root_dir = require("lspconfig.util").root_pattern("composer.json", ".git"),
          init_options = {
            ["language_server_phpstan.enabled"] = true,
            ["language_server_psalm.enabled"] = false,
            ["indexer.exclude_patterns"] = {
              "/vendor/**/Tests/**/*",
              "/vendor/**/tests/**/*",
              "/var/cache/**/*",
            },
            ["indexer.include_patterns"] = {
              "**/*.php",
            },
            ["completion_worse.completor.worse.collection.enabled"] = true,
            ["completion_worse.completor.worse.collection.limit"] = 100,
            ["composer.autoloader_path"] = "%project_root%/vendor/autoload.php",
            ["symfony.enabled"] = false,
            ["laravel.enabled"] = true,
            ["code_transform.class_new.variants"] = {
              ["laravel_request"] = {
                ["namespace"] = "App\\Http\\Requests",
                ["suffix"] = "Request",
              },
            },
          },
        },
        intelephense = {
          settings = {
            intelephense = {
              stubs = {
                "apache",
                "bcmath",
                "bz2",
                "calendar",
                "com_dotnet",
                "Core",
                "ctype",
                "curl",
                "date",
                "dba",
                "dom",
                "enchant",
                "exif",
                "fileinfo",
                "filter",
                "fpm",
                "ftp",
                "gd",
                "gettext",
                "gmp",
                "hash",
                "iconv",
                "imap",
                "intl",
                "json",
                "ldap",
                "libxml",
                "mbstring",
                "meta",
                "mysqli",
                "oci8",
                "odbc",
                "openssl",
                "pcntl",
                "pcre",
                "PDO",
                "pdo_ibm",
                "pdo_mysql",
                "pdo_pgsql",
                "pdo_sqlite",
                "pgsql",
                "Phar",
                "posix",
                "pspell",
                "readline",
                "Reflection",
                "session",
                "shmop",
                "SimpleXML",
                "snmp",
                "soap",
                "sockets",
                "sodium",
                "SPL",
                "sqlite3",
                "standard",
                "superglobals",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tidy",
                "tokenizer",
                "xml",
                "xmlreader",
                "xmlrpc",
                "xmlwriter",
                "xsl",
                "Zend OPcache",
                "zip",
                "zlib",
                "redis",
                "laravel",
              },
              environment = {
                includePaths = { "vendor/laravel/framework/src" },
              },
              files = {
                maxSize = 5000000,
              },
              completion = {
                insertUseDeclaration = true,
                fullyQualifyGlobalConstantsAndFunctions = true,
                triggerParameterHints = true,
                maxItems = 100,
              },
              diagnostics = {
                enable = true,
              },
            },
          },
        },
      },
    },
  },
}
